"""Identity plane: principals, certificates, tokens, delegation, downscoping, credential broker."""

from .auth_manager import (
    AccessEvent,
    AuthProvider,
    LocalAuthManager,
    PermissionDenied,
    ProviderKind,
    RetrieveCredentialsResult,
    make_local_gcp_auth_provider,
)
from .certs import AgentCertificate, LocalRuntimeCA, thumbprint
from .delegation import AuthorityContext, AuthorityMode
from .downscope import BoundaryEvaluator, BoundaryRule, CredentialAccessBoundary, build_boundary
from .principals import (
    AgentIdentity,
    PrincipalError,
    PrincipalSet,
    UserPrincipal,
    member_matches,
    org_trust_domain,
    project_trust_domain,
)
from .tokens import (
    BindingMismatch,
    Claims,
    DPoP,
    ExpiredToken,
    InsufficientScope,
    InvalidAudience,
    InvalidIssuer,
    InvalidSignature,
    ReplayDetected,
    TokenError,
    TokenIssuer,
    jwk_thumbprint,
    public_jwk,
)

__all__ = [
    "AccessEvent",
    "AgentCertificate",
    "AgentIdentity",
    "AuthProvider",
    "AuthorityContext",
    "AuthorityMode",
    "BindingMismatch",
    "BoundaryEvaluator",
    "BoundaryRule",
    "Claims",
    "CredentialAccessBoundary",
    "DPoP",
    "ExpiredToken",
    "InsufficientScope",
    "InvalidAudience",
    "InvalidIssuer",
    "InvalidSignature",
    "LocalAuthManager",
    "LocalRuntimeCA",
    "PermissionDenied",
    "PrincipalError",
    "PrincipalSet",
    "ProviderKind",
    "ReplayDetected",
    "RetrieveCredentialsResult",
    "TokenError",
    "TokenIssuer",
    "UserPrincipal",
    "build_boundary",
    "jwk_thumbprint",
    "make_local_gcp_auth_provider",
    "member_matches",
    "org_trust_domain",
    "project_trust_domain",
    "public_jwk",
    "thumbprint",
]
