#!/usr/bin/env python3
"""Regenerate the illustrative fixtures in ``moelab/fixtures/`` (deterministic; seconds; no torch).

Everything written here is **sample output in the documented format (illustrative)**: the right
shape and wording of what vLLM returns or prints, filled with numbers from this lab's own models so
that the parsers and exercises have something to read. None of it is a measurement. Replace each
file with your own run (the notebooks say how) and the same code reads it.

    python3 tools/make_fixtures.py

``tinymoe_curves.json`` is different: it is real output of ``moelab.tinymoe`` on the CPU and is
rewritten by ``python -m moelab.tinymoe --record`` (needs torch), not by this script.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from moelab import configs, ep, hooks, offload, stream  # noqa: E402

OUT = ROOT / "moelab" / "fixtures"
LABEL = ("sample output in the documented format (illustrative): generated by tools/make_fixtures.py "
         "from moelab's own models; not captured from a real model or GPU")


# ---- router traces in vLLM's --enable-return-routed-experts format ---------------------------------------
def routing_model(n_layers: int, n_experts: int, domains: list[str], seed: int = 7) -> dict:
    """An invented router: per layer a shared Zipf(0.5) popularity, mixed with a per-domain Zipf(1.0)
    popularity whose weight grows with depth (0.1 -> 0.5). Invented to exercise the analysis code."""
    rng = np.random.default_rng(seed)
    pops = {}
    for l in range(n_layers):
        base = rng.permutation(stream.zipf_popularity(n_experts, 0.5, seed=None))
        w = 0.1 + 0.4 * l / max(1, n_layers - 1)
        for d in domains:
            dom = rng.permutation(stream.zipf_popularity(n_experts, 1.0, seed=None))
            pops[(l, d)] = (1 - w) * base + w * dom
    return pops


def router_traces(path: Path = OUT / "router_traces_olmoe.json") -> None:
    m = configs.get("olmoe-1b-7b")
    domains = list(hooks.DOMAIN_PROMPTS)
    pops = routing_model(m.layers, m.n_experts, domains)
    rng = np.random.default_rng(11)
    responses = []
    for d in domains:
        for j, prompt in enumerate(hooks.DOMAIN_PROMPTS[d]):
            prompt_tokens, completion_tokens = 24 + 4 * j, 48
            n = prompt_tokens + completion_tokens - 1           # the last sampled token has no routing yet
            ids = np.stack([stream.sample_topk(pops[(l, d)], m.top_k, n, rng) for l in range(m.layers)], axis=1)
            responses.append({"domain": d, "prompt": prompt, "response": {
                "id": f"chatcmpl-illustrative-{d}-{j}", "object": "chat.completion", "model": m.hf_id,
                "choices": [{"index": 0, "message": {"role": "assistant", "content": "(illustrative; text omitted)"},
                             "finish_reason": "length",
                             "routed_experts": hooks.encode_routed_experts(ids.astype(np.uint8))}],
                "usage": {"prompt_tokens": prompt_tokens, "completion_tokens": completion_tokens,
                          "total_tokens": prompt_tokens + completion_tokens}}})
    doc = {"_label": LABEL, "model": m.hf_id, "num_experts": m.n_experts, "top_k": m.top_k,
           "server": (f"vllm serve {m.hf_id} --dtype half --max-model-len 4096 --cpu-offload-gb 3 "
                      "--cpu-offload-params experts --enable-return-routed-experts   # on a 16 GB T4"),
           "request_extra": {"routed_experts_prompt_start": 0}, "responses": responses}
    path.write_text(json.dumps(doc, indent=1))


# ---- `vllm bench serve` results for TP vs EP on 2 x T4 ---------------------------------------------------------
def bench_block(model: str, concurrency: int, n_prompts: int, input_len: int, output_len: int, itl_ms: float,
                ttft_ms: float, rng: np.random.Generator) -> str:
    """The printed block of vLLM v0.30.0's benchmarks/serve.py (default percentile metrics ttft,tpot,itl; P99)."""
    tpot = itl_ms * (1 + rng.uniform(0.01, 0.04))
    e2e_s = (ttft_ms + tpot * (output_len - 1)) / 1e3
    duration = e2e_s * n_prompts / concurrency * 1.02
    out_tok = n_prompts * output_len
    lines = [f"# {LABEL}",
             f"# vllm bench serve --base-url http://127.0.0.1:8000 --model {model} --dataset-name random "
             f"--random-input-len {input_len} --random-output-len {output_len} --num-prompts {n_prompts} "
             f"--max-concurrency {concurrency} --ignore-eos",
             "{s:{c}^{n}}".format(s=" Serving Benchmark Result ", n=50, c="=")]

    def row(label, value, fmt="{:<10.2f}"):
        lines.append("{:<40} ".format(label) + fmt.format(value))

    row("Successful requests:", n_prompts, "{:<10}")
    row("Failed requests:", 0, "{:<10}")
    row("Maximum request concurrency:", concurrency, "{:<10}")
    row("Benchmark duration (s):", duration)
    row("Total input tokens:", n_prompts * input_len, "{:<10}")
    row("Total generated tokens:", out_tok, "{:<10}")
    row("Request throughput (req/s):", n_prompts / duration)
    row("Output token throughput (tok/s):", out_tok / duration)
    row("Peak output token throughput (tok/s):", concurrency * 1e3 / itl_ms)
    row("Peak concurrent requests:", concurrency)
    row("Total token throughput (tok/s):", (out_tok + n_prompts * input_len) / duration)
    for name, header, mean in (("TTFT", "Time to First Token", ttft_ms),
                               ("TPOT", "Time per Output Token (excl. 1st token)", tpot),
                               ("ITL", "Inter-token Latency", itl_ms)):
        lines.append("{s:{c}^{n}}".format(s=header, n=50, c="-"))
        row(f"Mean {name} (ms):", mean)
        row(f"Median {name} (ms):", mean * (0.97 if name != "ITL" else 0.99))
        row(f"P99 {name} (ms):", mean * (1.9 if name == "TTFT" else 1.35))
    lines.append("=" * 50)
    return "\n".join(lines) + "\n"


def bench_outputs(out: Path = OUT) -> None:
    m, g, link = configs.get("olmoe-1b-7b"), configs.gpu("T4"), ep.LINKS["pcie-2xT4"]
    rng = np.random.default_rng(3)
    for lay in ep.LAYOUTS:
        for c in (1, 16):
            st = ep.ep_decode_step(m, g, lay, c, 256 + 64, link, ids=ep.routes(m, c, s=0.6, seed=c))
            itl = st.time * 1e3 * rng.uniform(0.97, 1.05)
            ttft = itl * (3 + 0.2 * c)
            text = bench_block(m.hf_id, c, 8 * c if c > 1 else 16, 256, 128, itl, ttft, rng)
            (out / f"bench_serve_olmoe_2xT4_{lay}_c{c}.txt").write_text(text)


# ---- vLLM start-up logs ---------------------------------------------------------------------------------------------
def startup_log(model_key: str, gpu_key: str, device_name: str, offload_gib: float, max_len: int, path: Path) -> None:
    m, g = configs.get(model_key), configs.gpu(gpu_key)
    f = offload.fit(m, g, "bf16" if g.bf16 else "fp16", max_model_len=max_len, offload_gib=offload_gib)
    loaded = f.weights_gib - offload_gib
    flags = ("--dtype half " if not g.bf16 else "") + f"--max-model-len {max_len}" + (
        f" --cpu-offload-gb {offload_gib:g} --cpu-offload-params experts" if offload_gib else "")
    cfg = f"/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/" \
          f"E={m.n_experts},N={m.expert_ff},device_name={device_name}.json"
    text = f"""# {LABEL}
# vllm serve {m.hf_id} {flags}   (values follow moelab.offload.fit with its default overhead)
INFO 09-26 10:00:01 [__init__.py:216] Automatically detected platform cuda.
INFO 09-26 10:00:03 [model.py:547] Resolved architecture: OlmoeForCausalLM
INFO 09-26 10:00:03 [model.py:1510] Using max model len {max_len}
INFO 09-26 10:00:41 [gpu_model_runner.py:2602] Model loading took {loaded:.2f} GiB memory and 37.214583 seconds
WARNING 09-26 10:00:44 [fused_moe.py:1164] Using default MoE config. Performance might be sub-optimal! Config file not found at {cfg}
INFO 09-26 10:00:52 [gpu_worker.py:298] Available KV cache memory: {f.kv_gib:.2f} GiB
INFO 09-26 10:00:52 [kv_cache_utils.py:1087] GPU KV cache size: {f.kv_tokens:,} tokens, Maximum concurrency for {max_len:,} tokens per request: {f.sessions:.2f}x
INFO 09-26 10:01:09 [core.py:210] init engine (profile, create kv cache, warmup model) took 27.95 s
INFO 09-26 10:01:10 [api_server.py:1634] Starting vLLM API server 0 on http://0.0.0.0:8000
"""
    path.write_text(text)


def main(out: Path = OUT) -> int:
    out.mkdir(parents=True, exist_ok=True)
    router_traces(out / "router_traces_olmoe.json")
    bench_outputs(out)
    startup_log("olmoe-1b-7b", "T4", "Tesla_T4", 3, 4096, out / "vllm_startup_olmoe_t4_offload.log")
    startup_log("olmoe-1b-7b", "L4", "NVIDIA_L4", 0, 4096, out / "vllm_startup_olmoe_l4.log")
    for p in sorted(out.iterdir()):
        print(f"{p.stat().st_size:>8,}  {p.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
