"""Render every generated deploy file from the policy (``python3 tools/render_manifests.py``).

The YAML you apply to kind and GKE, kind's cluster config and Docker's seccomp profile are all
generated from ``policy.py`` and ``seccomp.py``, so the admission predictor, the tests and
``kubectl apply`` read the same objects. ``stale()`` (and a test, and ``python3 -m sandboxlab
render --check``) fails when a committed file drifts from its generator or when a YAML file in a
generated directory no longer has one (the layer-03 lab's convention).
"""
from __future__ import annotations

import json
from pathlib import Path

from .. import seccomp
from . import manifests as m
from . import policy as P

LAB_ROOT = Path(__file__).resolve().parents[2]
GENERATED_DIRS = ("deploy/kind/manifests", "deploy/kind/workloads", "deploy/gke")
GENERATED_NOTE = "Generated by tools/render_manifests.py from sandboxlab/{src} - edit there and re-run."


def _doc(header: str, objs: list[dict], src: str = "k8s/policy.py") -> str:
    return m.to_yaml(*objs, header=f"{header}\n\n{GENERATED_NOTE.format(src=src)}")


def gke_runtime_class_reference() -> dict:
    """What GKE creates when a GKE Sandbox node pool exists (handler and scheduling: verify with
    ``kubectl get runtimeclass gvisor -o yaml``). Applied by ``apply.sh`` only if it is missing."""
    return m.runtime_class("gvisor", "gvisor", node_selector={"sandbox.gke.io/runtime": "gvisor"},
                           tolerations=[dict(P.GKE_SANDBOX_TAINT)])


def rendered_files() -> dict[str, str]:
    """Relative path (from the lab root) -> file content."""
    kind, gke = P.SandboxPolicy.kind(), P.SandboxPolicy.gke()
    out: dict[str, str] = {}
    out["deploy/kind/kind-config.yaml"] = m.to_yaml(P.kind_config(kind), header=(
        "kind cluster for the sandbox lab: control plane, a system worker, a sandbox worker (tainted by up.sh).\n"
        "The kubelet patch sets podPidsLimit for every node (kubeadm reads KubeletConfiguration from the first node).\n\n"
        + GENERATED_NOTE.format(src="k8s/policy.py")))
    for name, (header, objs) in P.render_all(kind).items():
        out[f"deploy/kind/manifests/{name}"] = _doc(header, objs)
    for name, (header, objs) in P.workloads(kind).items():
        out[f"deploy/kind/workloads/{name}"] = _doc(header, objs)
    out["deploy/kind/workloads/92-gvisor-in-kind.yaml"] = _doc(
        "MUST FAIL on kind: a RuntimeClass with handler runsc is accepted, and its pod ends Failed "
        "(kind's containerd has no runsc handler). On a gVisor-capable cluster the pod prints the Sentry's dmesg.",
        P.gvisor_in_kind())
    for name, (header, objs) in P.render_all(gke).items():
        out[f"deploy/gke/{name}"] = _doc(header + " (GKE Sandbox target: runtimeClassName gvisor, images from "
                                          "Artifact Registry - apply.sh substitutes LOCATION and PROJECT_ID.)", objs)
    for name, (header, objs) in P.workloads(gke).items():
        out[f"deploy/gke/workloads/{name}"] = _doc(header, objs)
    out["deploy/gke/reference/runtimeclass-gvisor.yaml"] = _doc(
        "REFERENCE ONLY: GKE creates RuntimeClass 'gvisor' with the first GKE Sandbox node pool (handler and\n"
        "scheduling fields: verify with `kubectl get runtimeclass gvisor -o yaml`). apply.sh applies this only if\n"
        "the object is missing.", [gke_runtime_class_reference()], "k8s/render.py")
    out["deploy/gke/optional/agent-sandbox.yaml"] = _doc(
        "OPTIONAL: the warm pool as kubernetes-sigs/agent-sandbox objects (install the controller first:\n"
        "deploy/gke/README.md). SandboxTemplate + SandboxWarmPool + one SandboxClaim.",
        P.agent_sandbox_objects(gke))
    out["deploy/docker/seccomp-sandbox.json"] = seccomp.to_json(seccomp.sandbox_profile())
    return out


def write(root: Path = LAB_ROOT) -> list[Path]:
    written = []
    for rel, text in rendered_files().items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        if not p.exists() or p.read_text() != text:
            p.write_text(text)
            written.append(p)
    return written


def orphans(root: Path = LAB_ROOT) -> list[str]:
    rendered = set(rendered_files())
    found = {p.relative_to(root).as_posix() for d in GENERATED_DIRS for p in (root / d).rglob("*.y*ml")}
    return sorted(found - rendered)


def stale(root: Path = LAB_ROOT) -> list[str]:
    drift = [rel for rel, text in rendered_files().items()
             if not (root / rel).exists() or (root / rel).read_text() != text]
    return drift + [f"{rel} (orphan: no generator)" for rel in orphans(root)]


def objects(target: str) -> list[tuple[str, dict]]:
    """Every rendered Kubernetes object for a target, as ``(file, object)``."""
    out = []
    for rel, text in rendered_files().items():
        if rel.endswith(".yaml") and rel.startswith(f"deploy/{target}/") and not rel.endswith("kind-config.yaml"):
            out += [(rel, o) for o in m.loads_all(text)]
    return out


def policy_json(target: str = "kind") -> str:
    """The proxy's allowlist as the pods see it (for notebooks)."""
    p = P.SandboxPolicy.kind() if target == "kind" else P.SandboxPolicy.gke()
    return json.dumps(P.proxy_config(p), indent=2)
