"""hooks.py — watch the router: which experts each token picks, per layer, and how skewed that is.

One idea: a router's decisions are cheap to capture and they are the input to every MoE serving
decision — how many experts a step streams, how uneven expert-parallel ranks are, which experts are
worth replicating (EPLB) or keeping on the GPU when others are offloaded. Capture them three ways:

* **forward hooks** on the router modules of a Hugging Face MoE (transformers v5 stores experts as
  fused 3D tensors, so there is no per-expert module to hook — hook the router). Most routers
  (``MixtralTopKRouter``, ``Qwen2MoeTopKRouter``, ``Qwen3MoeTopKRouter``, ``OlmoeTopKRouter``,
  ``GptOssTopKRouter``, ``DeepseekV3TopkRouter``) return ``(logits, scores, indices)``;
  ``GraniteMoeTopKRouter`` returns ``(indices, weights, logits)``; ``Llama4Router`` returns
  ``(scores, logits)`` with -inf-masked scores. ``output_router_logits=True`` gives only the logits.
* **vLLM**: ``vllm serve ... --enable-return-routed-experts``; each chat/completion choice then
  carries ``routed_experts``, a base64 ``.npy`` of shape ``(num_tokens - 1, num_layers, top_k)``.
* **the tiny MoE** in ``moelab.tinymoe`` (T0, torch on CPU): its router returns the HF layout.

The analysis is numpy only, so bundled traces work without torch. The bundled traces
(``fixtures/router_traces_olmoe.json``) are an illustrative sample in vLLM's documented format,
generated by ``tools/make_fixtures.py`` — not captured from OLMoE; capture your own at T1.
"""
from __future__ import annotations

import base64
import io
import json
import re
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from . import env

FIXTURES = Path(__file__).resolve().parent / "fixtures"


# ---- vLLM's routed_experts wire format -------------------------------------------------------
def decode_routed_experts(b64: str) -> np.ndarray:
    """base64 ``.npy`` -> int array ``[tokens - 1, layers, top_k]`` (vLLM ``numpy2base64``)."""
    return np.load(io.BytesIO(base64.b64decode(b64)), allow_pickle=False)


def encode_routed_experts(ids: np.ndarray) -> str:
    """The inverse: what vLLM puts in ``choices[i].routed_experts``."""
    buf = io.BytesIO()
    np.save(buf, np.asarray(ids), allow_pickle=False)
    return base64.b64encode(buf.getvalue()).decode("ascii")


@dataclass
class Trace:
    """Router decisions for one sequence: ``ids[token, layer, slot]`` = expert id."""
    ids: np.ndarray
    domain: str = ""
    source: str = env.ILLUSTRATIVE

    @property
    def tokens(self) -> int:
        return self.ids.shape[0]

    @property
    def layers(self) -> int:
        return self.ids.shape[1]


@dataclass
class TraceSet:
    model: str
    n_experts: int
    top_k: int
    traces: list = field(default_factory=list)
    label: str = ""

    def domains(self) -> list[str]:
        return sorted({t.domain for t in self.traces})

    def stacked(self, domain: str | None = None) -> np.ndarray:
        """All tokens of all (or one domain's) sequences: ``[tokens, layers, k]``."""
        return np.concatenate([t.ids for t in self.traces if domain is None or t.domain == domain])


def load_fixture(name: str = "router_traces_olmoe.json") -> TraceSet:
    """The bundled traces (illustrative), parsed exactly as a vLLM response would be."""
    doc = json.loads((FIXTURES / name).read_text())
    ts = TraceSet(doc["model"], doc["num_experts"], doc["top_k"], label=doc["_label"])
    for item in doc["responses"]:
        b64 = item["response"]["choices"][0]["routed_experts"]
        ts.traces.append(Trace(decode_routed_experts(b64), item["domain"], env.ILLUSTRATIVE))
    return ts


# ---- analysis (numpy) --------------------------------------------------------------------------
def utilisation(ids: np.ndarray, n_experts: int) -> np.ndarray:
    """Assignment counts ``[layers, n_experts]`` from ``ids[token, layer, k]``; each row sums to tokens x k."""
    ids = np.asarray(ids)
    return np.stack([np.bincount(ids[:, l, :].ravel(), minlength=n_experts) for l in range(ids.shape[1])])


def balancedness(counts: np.ndarray) -> np.ndarray:
    """vLLM EPLB's definition: mean tokens per expert / max tokens per expert (1.0 = perfect), per row."""
    counts = np.atleast_2d(counts).astype(float)
    return counts.mean(axis=1) / np.maximum(counts.max(axis=1), 1e-12)


def hot_experts(counts: np.ndarray, top: int = 4) -> list[list[tuple[int, float]]]:
    """Per layer, the ``top`` busiest experts and their share of that layer's assignments."""
    out = []
    for row in np.atleast_2d(counts):
        order = np.argsort(-row, kind="stable")[:top]
        out.append([(int(e), float(row[e] / row.sum())) for e in order])
    return out


def js_divergence(p: np.ndarray, q: np.ndarray) -> float:
    """Jensen-Shannon divergence in bits between two distributions (0 = same, 1 = disjoint)."""
    p, q = np.asarray(p, float) / np.sum(p), np.asarray(q, float) / np.sum(q)
    m = (p + q) / 2

    def kl(a, b):
        nz = a > 0
        return float(np.sum(a[nz] * np.log2(a[nz] / b[nz])))
    return 0.5 * kl(p, m) + 0.5 * kl(q, m)


def domain_divergence(ts: TraceSet) -> np.ndarray:
    """Per layer, the mean pairwise JS divergence between the domains' expert distributions."""
    doms = ts.domains()
    util = {d: utilisation(ts.stacked(d), ts.n_experts) for d in doms}
    layers = next(iter(util.values())).shape[0]
    out = np.zeros(layers)
    pairs = [(a, b) for i, a in enumerate(doms) for b in doms[i + 1:]]
    for l in range(layers):
        out[l] = np.mean([js_divergence(util[a][l], util[b][l]) for a, b in pairs])
    return out


def placement(n_experts: int, ep: int, strategy: str = "linear") -> np.ndarray:
    """Expert -> EP rank, as vLLM's ``--expert-placement-strategy`` describes it: "linear" gives rank 0
    experts [0, E/ep), "round_robin" gives expert e to rank e % ep (vLLM falls back to linear for
    models without expert groups, e.g. OLMoE; verify for your version)."""
    if n_experts % ep:
        raise ValueError("vLLM requires the expert count to divide by the EP size")
    e = np.arange(n_experts)
    return e // (n_experts // ep) if strategy == "linear" else e % ep


def rank_loads(counts: np.ndarray, ep: int, strategy: str = "linear") -> np.ndarray:
    """Assignments per EP rank ``[layers, ep]`` for per-layer expert counts ``[layers, E]``."""
    counts = np.atleast_2d(counts)
    where = placement(counts.shape[1], ep, strategy)
    return np.stack([np.bincount(where, weights=row, minlength=ep) for row in counts])


# ---- capturing from torch modules (lazy torch) -------------------------------------------------------
ROUTER_CLASS = re.compile(r"(TopKRouter|TopkRouter|Router)$")


def indices_from_output(module, output, top_k: int | None = None):
    """The ``[tokens, k]`` expert ids a router module returned, whatever its family's layout."""
    torch = env.torch()
    name = type(module).__name__
    if name.startswith("GraniteMoe"):                    # (indices, weights, logits)
        return output[0]
    if name == "Llama4Router":                           # (scores with -inf outside top-k, logits)
        k = top_k or getattr(module, "top_k", 1)
        return torch.topk(output[1], k, dim=-1).indices
    if isinstance(output, tuple) and len(output) == 3:   # (logits, scores, indices): HF v5 routers, tinymoe
        return output[2]
    raise TypeError(f"unknown router output layout for {name}: {type(output)}")


class RouterRecorder:
    """Forward hooks on every router module of ``model``; one ``[tokens, layers, k]`` array per forward.

        rec = RouterRecorder(model)          # finds *TopKRouter / *TopkRouter / *Router modules
        model(**inputs)
        ids = rec.pop()                      # np.ndarray [tokens, layers, k]
        rec.remove()
    """

    def __init__(self, model, top_k: int | None = None, pattern: re.Pattern = ROUTER_CLASS):
        self.top_k, self.buffers, self.handles, self.names = top_k, {}, [], []
        for name, mod in model.named_modules():
            if pattern.search(type(mod).__name__) and name:
                self.names.append(name)
                self.handles.append(mod.register_forward_hook(self._hook(name)))
        if not self.names:
            raise ValueError("no router modules found (looked for class names ending in Router/TopKRouter)")

    def _hook(self, name):
        def fn(module, args, output):
            idx = indices_from_output(module, output, self.top_k)
            self.buffers.setdefault(name, []).append(idx.detach().reshape(-1, idx.shape[-1]).cpu().numpy())
        return fn

    def pop(self) -> np.ndarray:
        """Everything recorded since the last pop, stacked in module order: ``[tokens, layers, k]``."""
        per_layer = [np.concatenate(self.buffers.get(n, [])) for n in self.names]
        self.buffers = {}
        return np.stack(per_layer, axis=1)

    def remove(self) -> None:
        for h in self.handles:
            h.remove()
        self.handles = []


# ---- T1 capture paths (need a GPU and downloads; never run in tests) ---------------------------------
DOMAIN_PROMPTS = {
    "code": ["def quicksort(xs):\n    if len(xs) <= 1:\n        return xs\n    pivot = xs[0]\n",
             "import numpy as np\n\nclass RingBuffer:\n    def __init__(self, n):\n"],
    "math": ["Let x be a real number such that x^2 - 5x + 6 = 0. Then the two solutions are",
             "The integral of sin(x) from 0 to pi equals 2 because the antiderivative"],
    "prose": ["The harbour town woke slowly; fishermen mended nets while the bakery",
              "In the spring of that year the committee met to discuss the new library"],
    "chinese": ["今天天气很好，我们一起去公园散步，然后", "中国的历史非常悠久，从古代到现在"],
}


def capture_hf(model_id: str, prompts: dict | None = None, dtype: str = "float16") -> TraceSet:
    """T1: load a Hugging Face MoE (downloads weights), run each prompt once, record the routers.
    ``pip install transformers accelerate``; a T4 fits OLMoE-1B-7B in fp16 (13.8 GB) for short prompts."""
    torch = env.torch()
    import transformers  # noqa: PLC0415 — T1 only
    tok = transformers.AutoTokenizer.from_pretrained(model_id)
    model = transformers.AutoModelForCausalLM.from_pretrained(model_id, dtype=getattr(torch, dtype), device_map="auto")
    cfg = model.config
    n_experts = getattr(cfg, "num_experts", None) or getattr(cfg, "num_local_experts", None) or cfg.n_routed_experts
    rec = RouterRecorder(model, top_k=cfg.num_experts_per_tok)
    ts = TraceSet(model_id, int(n_experts), int(cfg.num_experts_per_tok), label=env.MEASURED)
    try:
        with torch.no_grad():
            for dom, texts in (prompts or DOMAIN_PROMPTS).items():
                for text in texts:
                    ids = tok(text, return_tensors="pt").to(model.device)
                    model(**ids)
                    ts.traces.append(Trace(rec.pop(), dom, env.MEASURED))
    finally:
        rec.remove()
    return ts


def capture_vllm(url: str, model: str, n_experts: int, top_k: int, prompts: dict | None = None,
                 max_tokens: int = 32, headers: dict | None = None) -> TraceSet:
    """T1: ask a ``vllm serve --enable-return-routed-experts`` server; each response carries the
    routing of the prompt and the generated tokens (all but the last)."""
    import urllib.request  # noqa: PLC0415
    ts = TraceSet(model, n_experts, top_k, label=env.MEASURED)
    for dom, texts in (prompts or DOMAIN_PROMPTS).items():
        for text in texts:
            body = {"model": model, "messages": [{"role": "user", "content": text}], "max_tokens": max_tokens,
                    "temperature": 0, "routed_experts_prompt_start": 0}
            req = urllib.request.Request(url.rstrip("/") + "/v1/chat/completions", data=json.dumps(body).encode(),
                                         headers={"Content-Type": "application/json", **(headers or {})})
            with urllib.request.urlopen(req, timeout=300) as r:  # noqa: S310
                choice = json.loads(r.read())["choices"][0]
            if not choice.get("routed_experts"):
                raise RuntimeError("no routed_experts in the response: start vllm with --enable-return-routed-experts")
            ts.traces.append(Trace(decode_routed_experts(choice["routed_experts"]), dom, env.MEASURED))
    return ts
