"""Render every generated manifest under ``deploy/`` from the builders.

The YAML you apply is generated from ``k8sgpu.scenarios`` (kind) and ``k8sgpu.gke`` (GKE), so
the predictor, the linter and the tests all read the same objects that ``kubectl apply`` sends.
Run ``python tools/render_manifests.py`` after editing either module; a test fails if the
committed files drift.
"""
from __future__ import annotations

from pathlib import Path

from . import gke, scenarios
from .manifests import to_yaml

LAB_ROOT = Path(__file__).resolve().parents[1]
GENERATED_NOTE = "Generated by tools/render_manifests.py from k8sgpu/{src} - edit there and re-run."


def _doc(header: str, objs: list[dict], src: str) -> str:
    return to_yaml(*objs, header=f"{header}\n\n{GENERATED_NOTE.format(src=src)}")


def rendered_files() -> dict[str, str]:
    """Relative path (from the lab root) -> file content."""
    out: dict[str, str] = {}
    for fname, (header, objs) in scenarios.kueue_setup().items():
        out[f"deploy/kind/manifests/{fname}"] = _doc(header, objs, "scenarios.py")
    header, objs = scenarios.kwok_setup()
    out["deploy/kind/manifests/kwok-fleet-queues.yaml"] = _doc(header, objs, "scenarios.py")
    for sc in scenarios.SCENARIOS.values():
        for fname, (header, obj) in sc.objects.items():
            out[f"deploy/kind/workloads/{sc.dir}/{fname}"] = _doc(f"{sc.id}: {header}", [obj], "scenarios.py")
    for fname, (header, objs) in gke.gke_manifests().items():
        out[f"deploy/gke/{fname}"] = _doc(header, objs, "gke.py")
    return out


def write(root: Path = LAB_ROOT) -> list[Path]:
    written = []
    for rel, text in rendered_files().items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        if not p.exists() or p.read_text() != text:
            p.write_text(text)
            written.append(p)
    return written


def stale(root: Path = LAB_ROOT) -> list[str]:
    """Generated files that are missing or differ from what the builders produce."""
    return [rel for rel, text in rendered_files().items()
            if not (root / rel).exists() or (root / rel).read_text() != text]
