"""Render every generated manifest under ``deploy/`` from the builders.

The YAML you apply is generated from ``k8sgpu.scenarios`` (kind), ``k8sgpu.gke`` (GKE) and
``k8sgpu.gpuvm`` (a GPU VM with k3s), so the predictor, the linter and the tests all read the same
objects that ``kubectl apply`` sends. Run ``python tools/render_manifests.py`` after editing them;
``render --check`` (and a test) fails if a committed file drifts *or* if a YAML file under a
generated directory no longer has a generator (a renamed scenario would otherwise leave an orphan
that the README's apply loops still pick up).
"""
from __future__ import annotations

from pathlib import Path

from . import gke, gpuvm, scenarios
from .manifests import to_yaml

LAB_ROOT = Path(__file__).resolve().parents[1]
GENERATED_DIRS = ("deploy/kind/manifests", "deploy/kind/workloads", "deploy/gke", "deploy/gpu-vm")
GENERATED_NOTE = "Generated by tools/render_manifests.py from k8sgpu/{src} - edit there and re-run."


def _doc(header: str, objs: list[dict], src: str) -> str:
    return to_yaml(*objs, header=f"{header}\n\n{GENERATED_NOTE.format(src=src)}")


def rendered_files() -> dict[str, str]:
    """Relative path (from the lab root) -> file content."""
    out: dict[str, str] = {}
    for fname, (header, objs) in scenarios.kueue_setup().items():
        out[f"deploy/kind/manifests/{fname}"] = _doc(header, objs, "scenarios.py")
    header, objs = scenarios.kwok_setup()
    out["deploy/kind/manifests/kwok-fleet-queues.yaml"] = _doc(header, objs, "scenarios.py")
    for sc in scenarios.SCENARIOS.values():
        for fname, (header, obj) in sc.objects.items():
            out[f"deploy/kind/workloads/{sc.dir}/{fname}"] = _doc(f"{sc.id}: {header}", [obj], "scenarios.py")
    for fname, (header, objs) in gke.gke_manifests().items():
        out[f"deploy/gke/{fname}"] = _doc(header, objs, "gke.py")
    for fname, (header, objs) in gpuvm.gpuvm_manifests().items():
        out[f"deploy/gpu-vm/{fname}"] = _doc(header, objs, "gpuvm.py")
    return out


def write(root: Path = LAB_ROOT) -> list[Path]:
    written = []
    for rel, text in rendered_files().items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        if not p.exists() or p.read_text() != text:
            p.write_text(text)
            written.append(p)
    return written


def orphans(root: Path = LAB_ROOT) -> list[str]:
    """YAML files in the generated directories that no generator produces any more."""
    rendered = set(rendered_files())
    found = {p.relative_to(root).as_posix() for d in GENERATED_DIRS for p in (root / d).rglob("*.y*ml")}
    return sorted(found - rendered)


def stale(root: Path = LAB_ROOT) -> list[str]:
    """Generated files that are missing or differ from what the builders produce, plus orphans."""
    drift = [rel for rel, text in rendered_files().items()
             if not (root / rel).exists() or (root / rel).read_text() != text]
    return drift + [f"{rel} (orphan: no generator)" for rel in orphans(root)]
