"""recorded.py — per-sample outcomes of the *simulated* model on the eval set, for T0 notebooks.

One idea: test-time-compute estimators need many samples per question (pass@k needs n ≥ k), which is
what a GPU run produces in minutes and a laptop cannot produce at all. This file bundles such a table
— generated by :mod:`thinklab.fakemodel`, **not** by Qwen3 — so the estimators can be exercised
offline; at T1 the same table comes from ``collect()`` against a real server. Each record is one
(problem, mode, budget) with lists over samples: answers, correctness, reasoning and answer tokens,
finish reasons and a simulated reward-model score (a noisy scorer: correct answers score higher on
average, not always — so best-of-n with it is worse than with the verifier).

    python -m thinklab.thinking.recorded      # regenerate data/samples/sim_eval_records.jsonl
"""
from __future__ import annotations

import json
import random
from importlib import resources
from pathlib import Path

from .. import fakemodel
from .evalset import make_evalset, verify

FILE = "sim_eval_records.jsonl"
NOTE = "simulated model outcomes (illustrative): thinklab.fakemodel.SMALL on make_evalset(40, seed=0)"


def _rm_score(correct: bool, rng: random.Random) -> float:
    return round(rng.gauss(0.8 if correct else 0.0, 1.0), 3)


def generate_records(n_problems: int = 40, samples: int = 8, budgets: tuple = (128, 256, 512, 1024),
                     budget_samples: int = 4, seed: int = 0, card: fakemodel.ModelCard = fakemodel.SMALL) -> list:
    rows = []
    for p in make_evalset(n_problems, seed=seed):
        plan = [("off", None, samples), ("on", None, samples)] + [("budget", b, budget_samples) for b in budgets]
        for mode, b, k in plan:
            rng = random.Random(f"{p.id}|{mode}|{b}")
            outs = [fakemodel.generate(card, p.prompt, thinking=mode != "off", budget=b, seed=seed, sample_index=i)
                    for i in range(k)]
            correct = [bool(o.correct) for o in outs]
            rows.append({"id": p.id, "kind": p.kind, "difficulty": p.difficulty, "truth": p.answer, "mode": mode,
                         "budget": b, "answers": [o.answer for o in outs], "correct": correct,
                         "reasoning_tokens": [len(o.reasoning_tokens) + (len(fakemodel.EARLY_STOP.split()) if o.forced_stop else 0)
                                              for o in outs],
                         "answer_tokens": [len(o.content_tokens) for o in outs],
                         "finish": [o.finish_reason for o in outs],
                         "rm_scores": [_rm_score(c, rng) for c in correct]})
    return rows


def load() -> list:
    text = resources.files("thinklab.data").joinpath("samples", FILE).read_text()
    rows = [json.loads(line) for line in text.splitlines() if line.startswith("{")]
    return [r for r in rows if "_thinklab_note" not in r]


def collect(client, problems: list, samples: int = 8, budgets: tuple = (), budget_samples: int = 4,
            max_tokens: int = 8192, concurrency: int = 8) -> list:
    """T1: the same table from a real server (answers checked by the verifier; no reward model — ``rm_scores``
    are left empty). ``n=samples`` asks the server for several choices per request."""
    rows = []
    for p in problems:
        plan = [("off", None, samples), ("on", None, samples)] + [("budget", b, budget_samples) for b in budgets]
        for mode, b, k in plan:
            comps = client.chat(p.messages(), n=k, max_tokens=max_tokens, thinking=mode != "off", budget=b)
            comps = comps if isinstance(comps, list) else [comps]
            per_choice = [c.reasoning_tokens for c in comps]
            rows.append({"id": p.id, "kind": p.kind, "difficulty": p.difficulty, "truth": p.answer, "mode": mode,
                         "budget": b, "answers": [c.answer for c in comps], "correct": [verify(p, c.content) for c in comps],
                         "reasoning_tokens": [len((c.reasoning or "").split()) for c in comps] if None in per_choice else
                         [x // max(1, len(comps)) for x in per_choice],
                         "answer_tokens": [len((c.content or "").split()) for c in comps],
                         "finish": [c.finish_reason for c in comps], "rm_scores": []})
    return rows


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "data" / "samples" / FILE
    rows = generate_records()
    out.write_text(json.dumps({"_thinklab_note": NOTE}) + "\n" + "\n".join(json.dumps(r, separators=(",", ":")) for r in rows) + "\n")
    print(f"wrote {len(rows)} records to {out}")


if __name__ == "__main__":
    main()
