#!/usr/bin/env python3
"""Regenerate the nccl-tests *sample* outputs in gpurt/fixtures/ from a stated α-β model.

These files exist so the parser, the busbw re-check and the α-β fit can be exercised offline.
They are **illustrative, not measurements**: every time is ``α + S/B`` times a little seeded noise,
with α and B written into the file header. Replace them with your own ``all_reduce_perf`` logs
(deploy/any-gpu/run_nccl_tests.sh) to learn about real hardware.

    python3 tools/make_fixtures.py
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from gpurt.dist import busbw as bw  # noqa: E402

OUT = ROOT / "gpurt" / "fixtures"


def fmt_time(us: float) -> str:
    """nccl-tests prints fewer decimals as the time grows."""
    if us >= 10000:
        return f"{us:7.0f}"
    if us >= 100:
        return f"{us:7.1f}"
    return f"{us:7.2f}"


def modern(op="all_reduce", n=8, alpha_us=20.0, bus_gbps=400.0, noise=0.03, seed=7) -> str:
    rng = np.random.default_rng(seed)
    factor = bw.bus_factor(op, n)
    alg_asym = bus_gbps / factor  # GB/s
    sizes = [8 * 2 ** k for k in range(28)]  # 8 B .. 1 GiB
    lines = [
        "# SAMPLE OUTPUT in the documented nccl-tests format (illustrative, NOT a measurement): generated by",
        f"# tools/make_fixtures.py from t = alpha + S/B with alpha = {alpha_us} us and busbw -> {bus_gbps} GB/s "
        f"({op}, {n} ranks), {noise:.0%} noise.",
        "sample-node:41200:41200 [0] NCCL INFO Bootstrap : Using eth0:10.0.0.2<0>",
        "sample-node:41200:41262 [0] NCCL INFO Channel 00/16 :    0   1   2   3   4   5   6   7",
        "sample-node:41200:41262 [0] NCCL INFO Connected all rings",
        f"# nThread 1 nGpus {n} minBytes {sizes[0]} maxBytes {sizes[-1]} step: 2(factor) warmup iters: 5 iters: 20 "
        "agg iters: 1 validation: 1 graph: 0",
        "#",
        "# Using devices",
    ]
    lines += [f"#  Rank {r:2d} Group  0 Pid  41200 on sample-node device {r:2d} [0x{0x18 + 8 * r:02x}] SAMPLE-GPU (illustrative)"
              for r in range(n)]
    lines += [
        "#",
        "#                                                              out-of-place                       in-place          ",
        "#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong",
        "#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       ",
    ]
    busbws = []
    for s in sizes:
        p = bw.plan(op, s, n)
        size = p.size
        cells = []
        for _ in range(2):  # out-of-place, in-place
            t_us = (alpha_us + size / (alg_asym * 1e3)) * math.exp(rng.normal(0, noise))
            alg = size / t_us / 1e3
            bus = alg * factor
            busbws.append(bus)
            cells.append(f"  {fmt_time(t_us)}  {alg:6.2f}  {bus:6.2f}  {0:5d}")
        redop = "sum" if op in ("all_reduce", "reduce", "reduce_scatter") else "none"
        root = 0 if op in ("broadcast", "reduce") else -1
        lines.append(f"{size:12d}  {p.param_count:12d}  {'float':>8}  {redop:>6}  {root:6d}" + "".join(cells))
    lines += ["# Out of bounds values : 0 OK", f"# Avg bus bandwidth    : {sum(busbws) / len(busbws):.4f} ", "#", ""]
    return "\n".join(lines)


def legacy(op="all_gather", n=4, alpha_us=15.0, bus_gbps=18.0, noise=0.03, seed=11) -> str:
    """Older nccl-tests layout: no redop/root columns, a float 'error' column, no Group in device lines."""
    rng = np.random.default_rng(seed)
    factor = bw.bus_factor(op, n)
    alg_asym = bus_gbps / factor
    sizes = [1024 * 2 ** k for k in range(18)]  # 1 KiB .. 128 MiB
    lines = [
        "# SAMPLE OUTPUT in an older nccl-tests format (illustrative, NOT a measurement): generated by",
        f"# tools/make_fixtures.py from alpha = {alpha_us} us, busbw -> {bus_gbps} GB/s ({op}, {n} ranks).",
        f"# nThread 1 nGpus {n} minBytes {sizes[0]} maxBytes {sizes[-1]} step: 2(factor) warmup iters: 5 iters: 20 validation: 1",
        "#",
        "# Using devices",
    ]
    lines += [f"#   Rank {r:2d} Pid  10123 on sample-node device {r:2d} [0x{0x3b + r:02x}] SAMPLE-GPU (illustrative)" for r in range(n)]
    lines += [
        "#",
        "#                                             out-of-place                       in-place          ",
        "#       size         count    type     time   algbw   busbw  error     time   algbw   busbw  error",
        "#        (B)    (elements)             (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       ",
    ]
    busbws = []
    for s in sizes:
        p = bw.plan(op, s, n)
        cells = []
        for _ in range(2):
            t_us = (alpha_us + p.size / (alg_asym * 1e3)) * math.exp(rng.normal(0, noise))
            alg = p.size / t_us / 1e3
            busbws.append(alg * factor)
            cells.append(f"  {fmt_time(t_us)}  {alg:6.2f}  {alg * factor:6.2f}  0e+00")
        lines.append(f"{p.size:12d}  {p.param_count:12d}  {'float':>6}" + "".join(cells))
    lines += ["# Out of bounds values : 0 OK", f"# Avg bus bandwidth    : {sum(busbws) / len(busbws):.4f} ", ""]
    return "\n".join(lines)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "nccl_all_reduce_8gpu_sample.txt").write_text(modern())
    (OUT / "nccl_all_gather_4gpu_legacy_sample.txt").write_text(legacy())
    print("wrote", ", ".join(p.name for p in sorted(OUT.glob("nccl_*_sample.txt"))))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
