#!/usr/bin/env bash
# The colab-index job: the per-layer "Open in Colab" sections and COLAB.md are generated by
# tools/gen_colab_index.py; regenerating them must not change the tree. Standard library only.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
python tools/gen_colab_index.py
if ! git diff --exit-code --stat; then
  echo "::error::the Colab links are stale: run python3 tools/gen_colab_index.py and commit the result" >&2
  exit 1
fi
