#!/usr/bin/env python3
"""Write per-layer 'Open in Colab' link sections into each layer README, and a
short setup guide to COLAB.md. Idempotent: the per-layer section lives between
<!-- colab-links:start/end --> markers and is replaced on each run.

Run after sorting new content:  python3 tools/gen_colab_index.py
"""
import glob, os, re
from collections import OrderedDict
from pathlib import Path

BRANCH, REPO = "main", "aniryou/full-stack-agentic-engineer"
BADGE = "https://colab.research.google.com/assets/colab-badge.svg"
START, END = "<!-- colab-links:start -->", "<!-- colab-links:end -->"
def colab(p): return f"https://colab.research.google.com/github/{REPO}/blob/{BRANCH}/{p}"

total = 0
for layer in sorted(d for d in glob.glob('[0-9][0-9]-*') if os.path.isdir(d)):
    nbs = sorted(p for p in glob.glob(f'{layer}/**/*.ipynb', recursive=True)
                 if '.ipynb_checkpoints' not in p)
    total += len(nbs)
    body = ["## Run in Colab", "",
            f"One-time Colab setup is in [`../COLAB.md`](../COLAB.md). "
            f"Exercises are under `notebooks/` / `exercises/`; worked answers under `solutions/`.", ""]
    if not nbs:
        body.append("_No notebooks yet._")
    else:
        groups = OrderedDict()
        for nb in nbs:
            groups.setdefault(os.path.relpath(os.path.dirname(nb), layer), []).append(nb)
        for rel, items in groups.items():
            body.append(f"**`{rel}/`**" if rel != '.' else "**(layer root)**")
            for nb in items:
                body.append(f"- [![Open In Colab]({BADGE})]({colab(nb)}) `{os.path.basename(nb)}`")
            body.append("")
    section = START + "\n" + "\n".join(body).rstrip() + "\n" + END
    readme = Path(layer) / "README.md"
    t = readme.read_text() if readme.exists() else f"# {layer}\n"
    if START in t and END in t:
        t = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: section, t, flags=re.S)
    else:
        t = t.rstrip() + "\n\n" + section + "\n"
    readme.write_text(t)
    print(f"  {layer}: {len(nbs)} notebooks")

Path("COLAB.md").write_text('''# Running notebooks in Google Colab

Every notebook in this repo opens directly in Colab: click the **"Open in Colab"** badge next to it in
its layer's `README.md`. The repo is public, so there is nothing to set up. Each notebook's first cell
(tagged `colab-bootstrap`) is a no-op locally; on Colab it clones this repo, `cd`s into the notebook's
folder and pip-installs that lab's dependencies.

## Keeping your work
Colab opens a fresh copy from GitHub each time. To keep your edits, use *File -> Save a copy in Drive*
(or *Save a copy in GitHub* into your own fork).

## Redo an exercise
On Colab, reopen the notebook from its badge. Locally, `git restore <notebook>` returns it to the
committed blank; for percent-source labs, re-run the lab's `python3 tools/build_notebooks.py`.

_Per-layer notebook links are generated by `tools/gen_colab_index.py`._
''')
print(f"COLAB.md: setup guide only ({total} notebooks linked across layer READMEs)")
